language: rust
cache: cargo
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview --toolchain=nightly
script:
  - |
    pushd config_struct
    && cargo test --all-features
    && cargo fmt --all -- --write-mode=diff
    && cargo +nightly clippy --all-features -- -D clippy
    && popd

  - |
    pushd test_config_struct
    && cargo test
    && cargo test --release
    && cargo fmt --all -- --write-mode=diff
    && cargo +nightly clippy --all-features -- -D clippy
    && popd
