#!/bin/bash

set -e

echo -e "\033[36;1mRunning library tests:\033[0m"
cargo test --all-features

echo -e "\033[36;1mRunning integration tests:\033[0m"
(cd test_config_struct && cargo test)

echo -e "\033[36;1mRunning release-mode integration tests:\033[0m"
(cd test_config_struct && cargo test --release)

echo -e "\033[36;1mRunning rustfmt:\033[0m"
cargo fmt -- --check && (cd test_config_struct && cargo fmt -- --check)

echo -e "\033[36;1mRunning clippy:\033[0m"
cargo clippy --all-features -- -D clippy::all && (cd test_config_struct && cargo clippy --all-features -- -D clippy::all)

echo -e "\033[36;1mAll tests done!\033[0m"
