[package]
name = "config_struct"
version = "0.1.0"
authors = ["Pirh"]

[features]
default = []
toml-parsing = ["toml"]
yaml-parsing = ["serde_yaml"]

[dependencies]
toml = { version = "~0.4.5", optional = true }
serde_yaml = { version = "0.7.3", optional = true }
