name = "Config name"
number = 100
is_config = true
is_not_config = false
one_point_zero = 1.0
one_point_five = 1.5
floaty = 123.456789

coord = [-5.0, 5.0]
color = [0, 64, 128, 255]
words = [
    "one",
    "two",
    "three"
]
